// let userName = ["Anis", "Kamal", "Rana"];
// let userName: string[];
var userName;
var userId;
var use;
userId = [1, 3, 2, 5, 4];
use = [true, false, true];
userName = ["Anis", "Kamal", "Rana"];
console.log(userName);
console.log(userId);
console.log(use);
userId.sort();
userId.reverse();
console.log(userId);
